package net.md_5.bungee.protocol;

public enum OpCode
{

    BOOLEAN, BYTE, BYTE_INT, DOUBLE, FLOAT, INT, INT_3, INT_BYTE, ITEM, LONG, METADATA, OPTIONAL_MOTION, SHORT, SHORT_BYTE, SHORT_ITEM, STRING, USHORT_BYTE, OPTIONAL_WINDOW, BLOCK_CHANGE_ARRAY, BYTE_BYTE
}
